server:
  port: 10016

spring:
  application:
    name: client-b
  session:
    store-type: redis
    redis:
      host: 127.0.0.1
      password:
      port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:10006/eureka/
  instance:
    prefer-ip-address: true #不设可自己指定，true会自动获取本地ipv4地址
    ip-address: 127.0.0.1 #决定Eureka服务显示host
    hostname: ${eureka.instance.ip-address} #决定服务跳转host，必须指定
    #instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}