server:
    port: 10020



spring:
  application:
    name: gateway-service
  session:
    store-type: redis
    redis:
      host: 127.0.0.1
      password:
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: client-a
          uri: https://juejin.im/user/5aa50b96f265da23866f836e
          filters:
            - StripPrefix=1
            - RequestTime=true
            - SaveSession
            - RewritePath= /api/(?<path>.*), /$\{path}
          predicates:
            - Path=/api/**
        - id: lsc
          uri: http://localhost:10014
          predicates:
            - Path=/lsc/**
          filters:
            - StripPrefix=1
            - SaveSession
            - RewritePath=/test/(?<path>.*), /$\{path}
        - id: lsc2
          uri: http://localhost:10016
          predicates:
            - Path=/lsc2/**
          filters:
            - StripPrefix=1
            - SaveSession



eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:10006/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

